---
- name: install dependencies
  apt:
    name:
      - python3
      - python3-pip # Had to run apt-get update manually when I installed this for some reason
      - moreutils
      - nodejs
    state: present

- name: Install requests python package
  ansible.builtin.pip:
    name: requests

# Nodenv
- name: Clone nodenv
  git:
    repo: 'https://github.com/nodenv/nodenv.git'
    dest: "{{ nodenv_root }}"
    version: master
  become: true
  become_user: "{{ nonroot_login_user }}"

- name: Clone node-build
  git:
    repo: 'https://github.com/nodenv/node-build.git'
    dest: "/home/{{ nonroot_login_user }}/.nodenv/plugins/node-build"
    version: master
  become: true
  become_user: "{{ nonroot_login_user }}"

- name: Configure bash extension
  command:
    cmd: src/configure
    chdir: "{{ nodenv_root }}"
  become: true
  become_user: "{{ nonroot_login_user }}"

- name: Compile bash extension
  command:
    cmd: make -C src
    chdir: "{{ nodenv_root }}"
  become: true
  become_user: "{{ nonroot_login_user }}"

- name: Setup nodenv in .bashrc
  blockinfile:
    marker: "### {mark} ANSIBLE MANAGED BLOCK - NODENV ###"
    path: "/home/{{ nonroot_login_user}}/.bashrc"
    block: |
      export PATH="{{ nodenv_root }}/bin:$PATH"
      eval "$(nodenv init -)"

# Mila control
- name: mila control script
  copy:
    src: files/mila_ctrl.py
    dest: /usr/local/bin/mila_ctrl.py

- name: mila control cron script
  template:
    src: templates/mila_ctrl_cron.j2
    dest: /usr/local/bin/mila_ctrl_cron
    mode: "0700"

- name: Run mila control via cron every 5 minutes
  copy:
    content: "*/5 * * * * root /usr/local/bin/mila_ctrl_cron\n"
    dest: /etc/cron.d/mila_ctrl
    mode: "0644"

- name: Rotate mila control logs
  copy:
    src: files/mila_ctrl.logrotate.conf
    dest: /etc/logrotate.d/mila_ctrl
    mode: "0644"
    validate: logrotate -d %s

# tdlib for the Telegram api
# to build follow https://tdlib.github.io/td/build.html?language=JavaScript, follow instruction to only build tdjson/tdjson_static https://github.com/tdlib/td/tree/master?tab=readme-ov-file#building
- name: libtdjson
  copy:
    src: files/libtdjson.so.1.8.25-arm64
    dest: /usr/local/lib/libtdjson.so.1.8.25
    mode: "0755"
    owner: root
    group: root

- name: libtdjson link
  file:
    src: /usr/local/lib/libtdjson.so.1.8.25
    dest: /usr/local/lib/libtdjson.so
    owner: root
    group: root
    state: link
