---
- name: Create ddclient user
  user:
    name: ddclient
    password_lock: true
    create_home: false

- name: Install ddclient
  apt:
    name:
      - ddclient
    install_recommends: true
    state: present
  notify: force update ddns

- name: Create ddns heartbeat script
  template:
    src: templates/heartbeat.sh.j2
    dest: /var/local/ddclient-heartbeat
    mode: "0755"
  vars:
    heartbeat_url: https://hc-ping.com/f20f46ab-7171-4b56-bbfb-f9383bfa979f

- name: Template the config file
  template:
    src: templates/ddclient.conf.j2
    dest: /etc/ddclient.conf
    owner: ddclient
    mode: "0600"
  notify: force update ddns

- name: Run ddclient via cron every 10 minutes
  copy:
    content: "*/10 * * * * ddclient /usr/sbin/ddclient\n"
    dest: /etc/cron.d/ddclient
    mode: "0644"
