---
- name: Create ddclient user
  user:
    name: ddclient
    password_lock: true
    create_home: false

- name: Install ddclient
  apt:
    name:
      # - ddclient
      # Remove these deps and uncomment `install_recommends` once we start installing ddclient via apt
      - perl:any
      - libdata-validate-ip-perl
      - libjson-any-perl
      - libio-socket-ssl-perl
    # install_recommends: true
    state: present
  notify: force update ddns

# Get rid of these two when we install via apt again, need at least version 3.10
- name: Copy ddclient
  copy:
    src: files/ddclient
    dest: /usr/sbin/ddclient
    mode: "0755"
  notify: force update ddns
- name: Create conf directory
  file:
    path: /etc/ddclient
    mode: "0755"
    state: directory

- name: Template the config file
  template:
    src: templates/ddclient.conf.j2
    dest: /etc/ddclient/ddclient.conf
    owner: ddclient
    mode: "0600"
  notify: force update ddns

- name: Run ddclient via cron every 10 minutes
  copy:
    content: "*/10 * * * * ddclient /usr/sbin/ddclient\n"
    dest: /etc/cron.d/ddclient
    mode: "0644"
