---
- name: Install dependencies
  apt:
    name:
      - rsyslog
      - snapd
    state: present

- name: rsyslogd remote config
  copy:
    src: files/rsyslog-remote.conf
    dest: /etc/rsyslog.d/99-rsyslog-remote.conf
    mode: "0644"
    validate: rsyslogd -N1 -f %s
  notify: restart rsyslogd

- name: Create loguploader user
  user:
    name: loguploader
    password_lock: true
    create_home: true

- name: create remote log directory with correct permissions
  file:
    path: /var/log/remote
    owner: root
    group: loguploader
    mode: "0750"
    state: directory

- name: logrotate for rsyslogd remote
  copy:
    src: files/rsyslog-remote.logrotate.conf
    dest: /etc/logrotate.d/rsyslog-remote
    mode: "0644"
    validate: logrotate -d %s

- name: install awscli
  community.general.snap:
    name: aws-cli
    classic: true
    channel: v2/stable

- name: Create ~/.aws
  file:
    path: /home/loguploader/.aws
    mode: "0755"
    owner: loguploader
    state: directory

- name: Copy aws config
  copy:
    src: files/aws.loguploader.config
    dest: /home/loguploader/.aws/config
    mode: "0600"
    owner: loguploader

- name: Copy aws credentials
  template:
    src: templates/aws.loguploader.credentials.j2
    dest: /home/loguploader/.aws/credentials
    mode: "0600"
    owner: loguploader

- name: Create loguploader heartbeat script
  template:
    src: templates/heartbeat.sh.j2
    dest: /home/loguploader/heartbeat
    mode: "0755"
  vars:
    heartbeat_url: https://hc-ping.com/25c7b34e-e942-4b5e-a63a-2993c839f699
    heartbeat_status_arg: $1

- name: Copy uploader script to cron.daily
  copy:
    src: files/upload_logs
    # Prepend `z-` to ensure this runs after `logrotate`
    dest: /etc/cron.daily/z-upload_logs
    mode: "0755"
    owner: root
