---
# Disable armbian-ramlog. The interaction of their implementation with log rotation is
# buggy as hell and not worth the trouble. Better to just replace the SD card when it
# wears out from the extra writes.
# We only use zram for ramlog so we can disable that too
- name: disable armbian-ramlog and armbian-zram-config
  lineinfile:
    path: "{{item}}"
    search_string: 'ENABLED='
    line: 'ENABLED=false'
  notify: reboot
  with_list:
    - /etc/default/armbian-ramlog
    - /etc/default/armbian-zram-config

# armbian's logrotate.d configurations point to log.hdd so create a symlink
# so that we don't have to edit all those configurations. Ansible won't
# link a directory with contents, so we have to unmount it first.
- name: unmount /var/log.hdd
  mount:
    path: /var/log.hdd
    state: unmounted

- name: link /var/log.hdd
  file:
    src: /var/log
    dest: /var/log.hdd
    owner: root
    group: syslog
    state: link
    force: true # convert directory to symlink

- name: rsyslogd disable RepeatedMsgReduction
  lineinfile:
    path: /etc/rsyslog.conf
    search_string: '$RepeatedMsgReduction on'
    line: '#$RepeatedMsgReduction on'
  notify: restart rsyslogd

- name: rsyslogd remote config
  copy:
    src: files/rsyslog-remote.conf
    dest: /etc/rsyslog.d/99-rsyslog-remote.conf
    mode: "0644"
    validate: rsyslogd -N1 -f %s
  notify: restart rsyslogd

- name: Create loguploader user
  user:
    name: loguploader
    password_lock: true
    create_home: true

- name: create remote log directory with correct permissions
  file:
    path: /var/log/remote
    owner: syslog
    group: loguploader
    mode: "0750"
    state: directory

- name: logrotate for rsyslogd remote
  copy:
    src: files/rsyslog-remote.logrotate.conf
    dest: /etc/logrotate.d/rsyslog-remote
    mode: "0644"
    validate: logrotate -d %s

- name: install awscli
  community.general.snap:
    name: aws-cli
    classic: true
    channel: v2/stable

- name: Create ~/.aws
  file:
    path: /home/loguploader/.aws
    mode: "0755"
    owner: loguploader
    state: directory

- name: Copy aws config
  copy:
    src: files/aws.loguploader.config
    dest: /home/loguploader/.aws/config
    mode: "0600"
    owner: loguploader

- name: Copy aws credentials
  template:
    src: templates/aws.loguploader.credentials.j2
    dest: /home/loguploader/.aws/credentials
    mode: "0600"
    owner: loguploader

- name: Create loguploader heartbeat script
  template:
    src: templates/heartbeat.sh.j2
    dest: /home/loguploader/heartbeat
    mode: "0755"
  vars:
    heartbeat_url: https://hc-ping.com/25c7b34e-e942-4b5e-a63a-2993c839f699
    heartbeat_status_arg: $1

- name: Copy uploader script to cron.daily
  copy:
    src: files/upload_logs
    # Prepend `z-` to ensure this runs after `logrotate`
    dest: /etc/cron.daily/z-upload_logs
    mode: "0755"
    owner: root
