---
template:
  - sensor:
    - name: "Custom thermostat API data"
      unique_id: "custom_thermostat_api_data"
      state: >
        002
        {{ 1 if is_state('binary_sensor.on_vacation', 'on') else 0 }}
        {{ "{:05.1f}".format(min(999, max(0, states.sensor.most_recent_local_weather.state | float(0) + 100.0))) }}
        {{ "{:010d}".format(states.sensor.most_recent_local_weather.attributes.epoch | int(0)) }}
        {{ "{:03d}".format(states.sensor.airnow_air_quality_index.state | int(-1)) }}

automation:
  - alias: "Publish Custom Thermostat API Data to MQTT"
    description: "Publishes sensor.custom_thermostat_api_data state changes"
    trigger:
      - platform: state
        entity_id: sensor.custom_thermostat_api_data
    action:
      - service: mqtt.publish
        data:
          topic: "homeassistant/sensor/custom_thermostat_api_data/state"
          payload: "{{ states('sensor.custom_thermostat_api_data') }}"
          retain: true
