allow_anonymous false
password_file /etc/mosquitto/passwd

listener 8883 0.0.0.0
protocol mqtt
certfile /etc/mosquitto/certs/fullchain.pem
keyfile /etc/mosquitto/certs/privkey.pem

# Local plaintext listener for Docker containers on host network
listener 1883 127.0.0.1
protocol mqtt
